server:
  port: 8060

spring:
  application:
    name: GTWY-API-SERVICE

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
          filters:
            - StripPrefix=1

        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
          filters:
            - StripPrefix=1

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/project/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://<EUREKA_IP>:8761/eureka/
