server:
    port: 8060
spring:
  application:
    name: gtwy-api-service
cloud:
  gateway:
    routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
          - Path=/employee/**
      - id: department-service
        uri: lb://department-service
        predicates:
          - Path=/department/**
      - id: hr-service
        uri: lb://hr-service
        predicates:
          - Path=/hr/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/